# Generated by Django 6.1 on 2026-08-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryadjustment',
            old_name='quantity',
            new_name='quantity_changed',
        ),
    ]
