# Generated by Django 6.1 on 2026-08-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleitem_quantity_alter_saleitem_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cancellation_reason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancelled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancelled_by',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Owner', 'Owner')], max_length=10, null=True),
        ),
    ]
