# Generated by Django 6.1 on 2026-08-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_cancellation_reason_sale_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cancelled_by',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Owner', 'Owner')], max_length=20, null=True),
        ),
    ]
