# Generated by Django 6.1 on 2026-08-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_cancelled_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='cancellation_reason',
            new_name='cancel_reason',
        ),
    ]
